apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyego-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-eyego  
  template:
    metadata:
      labels:
        app: hello-eyego
    spec:
      containers:
        - name: eyego
          image: 010526266619.dkr.ecr.us-east-1.amazonaws.com/eygo-app:latest 
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ecr-secret  
